### ISSUE TITLE
Is allowance required?

### ISSUE THREAD

**Issue by kyscott18** [Uniswap/permit2#173]
I am wondering if the transfer by signature logic introduced here in combination with EIP 1271 removes the need for the approve + transferFrom flow and the allowance storage in the ERC20 standard if we were to start from scratch? Or is there some special cases when allowance still has extended functionality?

In a slightly tangential yet related note, is there any thought about introducing a transfer by signature scheme for custom defined data such as a [UniswapV3Pool position](https://github.com/Uniswap/v3-core/blob/main/contracts/UniswapV3Pool.sol#L97). The benefit of this would be that custody of the position could be separated from the helper functions that allow you to enter and exit a position. I think you could then still go back and wrap this in the ERC721 standard after the fact too.

**Comment by ewilz** [comment]
Hey @kyscott18, if I understand your first paragraph correctly, EIP 1271 + signature logic works great for contract wallets but not EOA's, but with Permit2 there's the option to sign a message w/ and EOA which performs a transfer without affecting allowances. I think the only downside to this is the EOA must sign this message and the tx, so that's two signatures (button presses) for every transaction, that might be seen as a UX downside.

The position could be separated from the helper functions mint/burn?
